services:
  - type: web
    name: image-segmentation
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src
    plan: free
    healthCheckPath: /
    autoDeploy: true 